add doc for new ra-limits-per-instant
farao-community/farao-community.github.io pull request #108
Opened 2024-02-20 12:09 UTC by MartinBelthle

Linked to this PR on open-rao: https://github.com/powsybl/powsybl-open-rao/pull/886

2024-02-20 13:51 UTC, pet-mit requested changes
I think there are some links to the removed parameters in other pages, for instance in the RA usage limits filler doc page

MB : I've checked and there don't seem to be any other links to this page. The one you specified existed but was broken that's why i missed it.

2024-02-20 13:51 UTC, pet-mit commented on pages/docs/input-data/crac/creation-parameters.md
> +This parameter limits the usage of remedial actions for given instants.
```suggestion
This parameter limits the usage of remedial actions for given instants. The instant ID must match an ID of an instant in the CRAC.  
```

2024-02-20 13:52 UTC, pet-mit requested changes
you should also update the CRAC page : 
- how to add limits
- examples

Not done yet.

2024-02-27 13:58 UTC, pet-mit requested changes

2024-02-28 08:49 UTC, MartinBelthle commented on pages/docs/input-data/crac/creation-parameters.md
> +    "max-pst-per-tso" : { },
This is equivalent but I wanted to show that the java code above would create an `RaUsageLimits` object with some empty fields.
I can change it but I'm not really convinced :/

2024-02-28 09:00 UTC, pet-mit commented on pages/docs/input-data/crac/creation-parameters.md
> +    "max-pst-per-tso" : { },
the idea of the java & json tabs is to expose to the user two ways of defining the limits, and they chose their preferred way. it's okay if exporting what is in the "java" tab does not yield exactly what is in the "json" tab. in reality, the user wouldn't write empty fields (and your example makes them think they have to)

2024-02-28 09:17 UTC, MartinBelthle commented on pages/docs/input-data/crac/creation-parameters.md
> +    "max-pst-per-tso" : { },
Okay I see, you convinced me :)

2024-02-28 09:46 UTC, pet-mit approved these changes

2024-02-28 09:46 UTC, merged