Csa 26 voltage monitoring update
farao-community/farao-community.github.io pull request #77
Opened 2023-09-12 14:24 UTC by GabrielPlante

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Documentation for user story CSA-26

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2023-09-13 07:04 UTC, pet-mit requested changes

2023-09-13 07:04 UTC, pet-mit commented on pages/docs/castor/voltage-monitoring/algorithm.md
> +      - If the RA is a topological action, apply it on the network
```suggestion
      - If the remedial action is not a network action, do not apply it and log a warning. Then move on to the next RA.
      - If the RA is a network action, apply it on the network
```

2023-09-13 07:04 UTC, pet-mit commented on pages/docs/castor/voltage-monitoring/result.md
> +"applied-cras": [
```suggestion
"applied-ras": [
```

2023-09-20 10:09 UTC, GabrielPlante commented on pages/docs/castor/voltage-monitoring/algorithm.md
> +- Apply optimal preventive remedial actions from RaoResult on the network
I simply copy pasted and adapted the same algorithm as described in the user story, it was inverted there but I can revert those line

2023-09-20 10:12 UTC, GabrielPlante commented on pages/docs/castor/voltage-monitoring/algorithm.md
> +      - If the RA is a topological action, apply it on the network
Done !

2023-09-20 10:12 UTC, GabrielPlante commented on pages/docs/castor/voltage-monitoring/result.md
> +"applied-cras": [
Done !

2023-09-21 15:11 UTC, pet-mit commented on pages/docs/castor/voltage-monitoring/algorithm.md
> +- Apply optimal preventive remedial actions from RaoResult on the network
yes, revert this change please

2023-09-22 06:37 UTC, GabrielPlante commented on pages/docs/castor/voltage-monitoring/algorithm.md
> +- Apply optimal preventive remedial actions from RaoResult on the network
Done !

2023-09-22 09:31 UTC, pet-mit approved these changes

2023-09-22 09:31 UTC, merged