Add CRAC CSA page
farao-community/farao-community.github.io pull request #78
Opened 2023-09-14 12:10 UTC by bqth29

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

Adds presentation of CSA profiles and how to import the CSA CRAC.

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2023-09-14 12:17 UTC, pet-mit requested changes

2023-09-25 13:40 UTC, jipea requested changes

2023-09-25 13:40 UTC, jipea commented on pages/docs/input-data/crac/csa.md
> +The CNEC is imported only if the `isCritical` and `normalEnabled` fields are both set to `true`. If the `inBaseCase`
The CNEC is also imported if these fields are missing, because some TSO won't use them.

2023-09-26 07:27 UTC, pet-mit approved these changes

2023-09-26 07:27 UTC, merged