[CSA-25] Implement voltage remedial actions
farao-community/farao-community.github.io pull request #80
Opened 2023-09-21 08:53 UTC by GabrielPlante

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2023-09-21 15:12 UTC, pet-mit requested changes

2023-09-21 15:12 UTC, pet-mit commented on pages/docs/input-data/crac/json/remedial-actions.md
> +"voltageCnecId" : "voltage-cnec-id"
indent these lines

2023-09-25 08:17 UTC, GabrielPlante commented on pages/docs/input-data/crac/json/remedial-actions.md
> +"voltageCnecId" : "voltage-cnec-id"
Done !

2023-09-25 08:37 UTC, pet-mit approved these changes

2023-09-25 08:37 UTC, merged